### ISSUE TITLE
firmware

### ISSUE THREAD

**Issue by ZippingBoat9588** [scooterteam/bw-flasher#1]
so if i use the modded firmware and want to go back looking normal, how do i change it so the scooter goes 20 km\h and not higher

**Comment by ZippingBoat9588** [comment]
And a request of me is could you please add a cfw create Tool? Would be nice to set Speed manual :D also If you do that please add for German static Brake light :)

**Comment by ZippingBoat9588** [comment]
So the downloaded untouched Firmware is an German Firmware?

**Comment by encryptize** [comment]
> So the downloaded untouched Firmware is an German Firmware, and Drives 5,15,20 kmh?

Yes.

**Comment by ZippingBoat9588** [comment]
Alr well thats it thanks Just waiting now for the cable and Happy flashing :)
